### PR TITLE
BidMachine/1.9.3.0

### PR DESCRIPTION
**Pull request by NikitaCherep**

### CODE REVIEW

**Comment by thomasmso** [comment]
Thank you for the PR - will review this weekend

**Comment by applovinjosh** [comment]
Hello @NikitaCherep, can you provide some credentials for testing your adapters?  It looks like I will need at least a source ID and some bid responses, but if you can assist that would be great.

**Comment by meeeeeepo** [comment]
@applovinjosh  Hello!
Source Id is 209
I am also providing server responses for s2s connection and bidresponses (payloads) which should be passed to SDK
- Banner server response - https://run.mocky.io/v3/3953b39e-b171-4afc-980d-a78e690e7450
- Banner bidresponse (payload) - https://run.mocky.io/v3/b27b47d7-f508-4b95-8608-fa7aba2be737
- Interstitial server response - https://run.mocky.io/v3/7c9f17fb-98a8-4a1b-8aa7-ccaf2032eb58
- Interstitial bidresponse (payload) - https://run.mocky.io/v3/5888e34f-1c35-464b-b061-05a3758b3aca
- Rewarded server response - https://run.mocky.io/v3/efcf97f2-6b94-4eec-af9f-4279b5cef52e
- Rewarded bidresponse (payload) - https://run.mocky.io/v3/0527c25c-672d-4244-94c3-346c7edd8266
- Native server response - https://run.mocky.io/v3/bf835e65-50b4-405f-a6ab-6c577cf22719
- Native bidresponse (payload) - https://run.mocky.io/v3/9f1d3aa0-077d-40bd-84bd-f5cec77affa3

**Comment by applovinjosh** [comment]
Hi @meeeeeepo thanks for the responses.  Can you confirm that you native payload is working for you?  The other formats are working, but I get the following using your native payload:
	iOS - "payload string contain unsuported format"	
	Android - "BidPayload does not contain Response or URL"

**Comment by meeeeeepo** [comment]
Hey @applovinjosh 
Looks like i shared wrong payload for native, my bad
Sharing new one - https://run.mocky.io/v3/4d5dc77e-7d89-466b-9a4d-4a77b1242e11
It should work fine

**Comment by thomasmso** [comment]
Live: https://github.com/AppLovin/AppLovin-MAX-SDK-Android/commit/3db4565b54408703d83fd488fd9fe145e68c26b4

**Pull request closed without merging**
