### PR TITLE
fix/listener_interface_updates

### PR DESCRIPTION
**Pull request by Lorenzo45**

### CODE REVIEW

**Comment by gubatron** [comment]
Unrelated:

We are getting about 30 crashes a day with com.applovin:applovin-sdk:9.14.4
Screen Shot 2020-10-12 at 9 42 47 PM

**Review by thomasmso — APPROVED** [review]

**Comment by gubatron** [comment]
@thomasmso  what is a good place to report crashes?

**Comment by thomasmso** [comment]
@gubatron - You can contact your account manager who will help us prioritize internally. But as far as this crash goes - we'll have a fixed SDK within 2 days, just make sure you're following releases on this repo :).

**Comment by gubatron** [comment]
Thanks (acct manager has gone M.I.A. for a couple weeks now, wish we had dev to dev mechanisms like simply reporting issues here)

**Comment by thomasmso** [comment]
@gubatron - Who The issue is mostly on prioritization. With that said, could you email me your AM's name and your AppLovin email to thomas.so@applovin.com?

**Pull request closed without merging**
